export default function Privacy() {
  return (
    <article className="prose mx-auto max-w-2xl px-6 py-12 dark:prose-invert">
      <h1>Privacy</h1>
      <p>
        <strong>Draft.</strong> The production Privacy Policy is generated by Termly and
        embedded here before launch. Key provisions we intend to include:
      </p>
      <ul>
        <li>We collect public GitHub data (usernames, join dates, public counts) for analysis.</li>
        <li>
          We collect account data (email, GitHub OAuth, Stripe customer) for paid users. Tokens
          are encrypted at rest.
        </li>
        <li>We honor removal requests for individual profiles via <a href="/removal">this form</a>.</li>
        <li>We respect GDPR/CCPA rights; contact us at <a href="mailto:privacy@tcabr.example">privacy@tcabr.example</a>.</li>
      </ul>
    </article>
  );
}
