export default function Terms() {
  return (
    <article className="prose mx-auto max-w-2xl px-6 py-12 dark:prose-invert">
      <h1>Terms of Service</h1>
      <p>
        <strong>Draft.</strong> The production Terms are generated by Termly and embedded here
        before launch. Key provisions we intend to include:
      </p>
      <ul>
        <li>No warranty; analysis is provided as-is for informational and satirical purposes.</li>
        <li>No guarantees of accuracy; scores are statistical signals, not verdicts.</li>
        <li>No commercial re-use of scan data without permission.</li>
        <li>
          Users agree to indemnify TCABR for any misuse of reports, including republication
          as factual claims.
        </li>
      </ul>
    </article>
  );
}
